sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: f6iEvduKaWNK0SM+aVFg9QX+fO30dXuLDviG++Ff+fXa+7v3/pKwKxEiJSkNuf/D8Iga3c7DGfRvIJhvIFyNwiEgOwDntUKcKOT0pIgLHysk/ghDMv9NbEtbjXXxZlRbDTZg1uFe/QhugKQDxKM14RK9Zy+g0xKFCh61tdF2sqUWvHu0IsTmhWyB0gh5xFJiv4v2JjxJK1XHF2Hy8gweJETQBTtXrCmqF7DGsRzDfRGLRT5TgPMBf29L8QuxrAiCVgFNjMbBstT/o057n57vwSCfq9h02UbpHlRF//Eo6DsUddj6np5BsMUujt74tSKlLQ16DnjQR7cKwsDs9K88Cnag+E6+UWivFteblkpJOMtIp4BTcJrWXkGRaEETqQN/GZ3yMxE0PWVJvvmkN+CGx+rR1b22Nfn+4aFhakzALZEm3EEvMprRXMoS086j+uCa+400KAb7+YoeH7eInqKUVOW18wBELPu+jQUgDSQ2FzwQ0HWNMd7VKgSN0mdY0Vas2YwCVS4M3adGxtpyNj2azl0Rzmwon1lMQaBLkYxLJhuxjFmY6+w5PaNGuEsZiBu4nvSfcDaMelEtAtnJJp5VVF4Yr2v04KS0bhq4wgyRvyledeweyJS4Ynz1eIzG8ga+OoI8DQcIEZAPuJohB3y4HGoQMd5X2WZxCqv4ugVCfTs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Macbeth_2264
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy